---
- hosts: tag_Name_monolithic_Instance
  become: yes
  vars:
    ansible_ssh_private_key_file: "/etc/ansible/SaiCharanKeyPair.pem"
    ansible_ssh_user: "ubuntu"

  tasks:
    - name: Install web server (Ubuntu)
      apt:
        name: apache2
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Install web server (RHEL-based)
      dnf:
        name: httpd
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Ensure web server is started and enabled
      service:
        name: "{{ 'apache2' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"
        state: started
        enabled: yes

    - name: Install Git
      package:
        name: git
        state: present

    - name: Clone frontend code from GitHub
      git:
        repo: https://github.com/lit/lit.git
        dest: /var/www/html/
        version: frontend
      notify: Restart web server

  handlers:
    - name: Restart web server
      service:
        name: "{{ 'apache2' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"
        state: restarted
