---
- hosts: aws_ec2
  become: yes
  connection: ssh
  user: ec2-user

  vars:
    ansible_ssh_private_key_file: "/etc/ansible/SaiCharanKeyPair.pem"
    ansible_ssh_user: "ec2-user"

  tasks:
    - name: Install Nginx web server
      yum:
        name: nginx
        state: present

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Install Git
      yum:
        name: git
        state: present

    - name: Clone the source code from GitHub
      git:
        repo: "https://github.com/devops0014/aws-node-js.git"
        dest: /var/www/html/
        version: main

    - name: Configure Nginx to serve content from /var/www/html
      copy:
        dest: /etc/nginx/conf.d/default.conf
        content: |
          server {
              listen 80;
              server_name _;
              root /var/www/html;
              index index.html index.htm;

              location / {
                  try_files $uri $uri/ =404;
              }
          }

    - name: Restart Nginx to apply changes
      service:
        name: nginx
        state: restarted
